# Generated by Django 3.2.9 on 2022-02-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_usermodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='email',
            new_name='uemail',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='uname',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='phone',
            new_name='uphone',
        ),
    ]
