# Generated by Django 3.2.9 on 2022-02-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20220210_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='aboutu',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='freelance',
            field=models.BooleanField(default=False),
        ),
    ]
