# Generated by Django 3.2.9 on 2022-02-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20220211_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
