# Generated by Django 3.2.9 on 2022-02-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_usermodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
