# Generated by Django 3.2.9 on 2022-02-15 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20220214_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitermodel',
            old_name='uname',
            new_name='rname',
        ),
        migrations.RenameField(
            model_name='recruitermodel',
            old_name='uphone',
            new_name='rphone',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 15, 9, 22, 933732)),
        ),
    ]
