# Generated by Django 3.2.9 on 2022-02-15 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20220215_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitermodel',
            name='remail',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 15, 16, 2, 436525)),
        ),
    ]
