# Generated by Django 3.2.9 on 2022-02-20 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_alter_usermodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 22, 32, 38, 585731)),
        ),
    ]
