# Generated by Django 3.2.9 on 2022-01-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=30)),
                ('f_phoneno', models.CharField(blank=True, max_length=12)),
                ('f_email', models.EmailField(max_length=254)),
                ('f_message', models.TextField(max_length=500)),
            ],
        ),
    ]
