# Generated by Django 3.2.9 on 2022-02-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qname', models.CharField(blank=True, max_length=30)),
                ('qphone', models.CharField(blank=True, max_length=12)),
                ('qemail', models.EmailField(blank=True, max_length=254)),
                ('qbussiness', models.CharField(blank=True, max_length=30)),
                ('qnoofpages', models.IntegerField(blank=True)),
                ('stack', models.CharField(blank=True, max_length=30)),
                ('qbudget', models.IntegerField(blank=True)),
                ('qteam', models.BooleanField(blank=True)),
                ('qtype', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
